services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mindy\Bundle\MindyBundle\:
        resource: '../../*'
        exclude: '../../{Model,Tests,vendor}'
