parameters:
    mindy.exception_listener.enable: false

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mindy\Bundle\MindyBundle\:
        resource: '../../*'
        exclude: '../../{Model,Tests,vendor}'

    Mindy\Bundle\MindyBundle\EventSubscriber\ExceptionEventSubscriber:
        public: true
        arguments:
            $enable: '%mindy.exception_listener.enable%'
